# Este flujo de trabajo usa acciones que no están certificadas por GitHub.
# Son proporcionadas por terceros y están gobernadas por términos de servicio, política de privacidad y documentación de soporte separados.
# Este flujo de trabajo construirá un proyecto Java con Gradle y almacenará en caché/restaurará las dependencias para mejorar el tiempo de ejecución del flujo de trabajo.
# Para más información, consulta: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    paths:
      -'registry-service/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Configura Gradle para su uso óptimo en GitHub Actions, incluyendo la caché de dependencias descargadas.
    # Más información: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # NOTA: El Gradle Wrapper es la forma predeterminada y recomendada de ejecutar Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # Si tu proyecto no tiene configurado el Gradle Wrapper, puedes usar la siguiente configuración para ejecutar Gradle con una versión específica.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

